In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("PreTest.csv")
df = df.drop([0, 1]).reset_index(drop=True)
df = df[(df["DiscNoPers"] == "1") | (df["DiscPers"] == "1")]

df = df.drop(columns=['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress',
       'Duration (in seconds)', 'Finished', 'RecordedDate', 'DiscNoPers', 'DiscPers',
       'RecipientLastName', 'RecipientFirstName', 'RecipientEmail',
       'ExternalReference', 'LocationLatitude', 'LocationLongitude',
       'DistributionChannel', 'UserLanguage', 'Q_RecaptchaScore', '__js_NextPage_MS',
       '__js_Prompt1_Clicked', '__js_Prompt2_Clicked', '__js_Prompt3_Clicked', '__js_Prompt4_Clicked',
       '__js_AllPromptsClicked', 'Gradio', 'PROLIFIC_PID', 'ResponseId', 'Q_RecaptchaStatus', 'Q_RecaptchaError',
       'AC1', 'AC2', 'AC3', 'AC4'])

warmth_columns = ['W_Q1_1', 'W_Q1_2', 'W_Q1_3', 'W_Q1_4']
personalization_columns = ['MC_Personal_1', 'MC_Personal_2']
for col in [warmth_columns, personalization_columns]:
    for c in col:
        df[c] = pd.to_numeric(df[c], errors='coerce')

df["PreDV_Slider_1"] = pd.to_numeric(df["PreDV_Slider_1"], errors='coerce')
df["PostDV_Slider_1"] = pd.to_numeric(df["PostDV_Slider_1"], errors='coerce')
df["Slider_Difference"] = df["PostDV_Slider_1"] - df["PreDV_Slider_1"]
df["DV_Binary_Diff"] = np.where(((df["PreDV_Binary"] == "1") & (df["PostDV_Binary"] == "1")) | ((df["PreDV_Binary"] == "2") & (df["PostDV_Binary"] == "2")), 
0, np.where((df["PreDV_Binary"] == "1") & (df["PostDV_Binary"] == "2"), 1, -1))

df["Warmth_Check"] = df[warmth_columns].mean(axis=1)
df["Personalization_Check"] = df[personalization_columns].mean(axis=1)

In [68]:
df.columns

Index(['PID', 'Age', 'Education', 'Work', 'Hobbies', 'PreDV_Slider_1',
       'PreDV_Binary', 'PostDV_Slider_1', 'PostDV_Binary', 'MC_Personal_1',
       'MC_Personal_2', 'W_Q1_1', 'W_Q1_2', 'W_Q1_3', 'W_Q1_4', 'CTC_1',
       'CTC_2', 'CTI_1', 'CTI_2', 'CTI_3', 'ET_1', 'ET_2', 'ET_3', 'DL_1',
       'DL_2', 'DL_3', 'DL_4', 'DL_5', 'DL_6', 'DL_7', 'UF_Q1',
       'Personality_1', 'Personality_2', 'Personality_3', 'Personality_4',
       'Personality_5', 'Personality_6', 'Personality_7', 'Personality_8',
       'Personality_9', 'Personality_10', 'ResponseID', 'AC_City', 'AC_Expert',
       'AC_Risk', 'AC_Assistant', 'Warmth', 'Personalization',
       'Slider_Difference', 'Warmth_Check', 'Personalization_Check'],
      dtype='object')

In [86]:
df.groupby(["Warmth", "Personalization", "DV_Binary_Diff"]).count()["PID"]

Warmth  Personalization  DV_Binary_Diff
0       0                0                 1
                         1                 1
        1                0                 1
                         1                 2
1       0                0                 2
                         1                 1
        1                0                 1
                         1                 1
Name: PID, dtype: int64

In [83]:
df[["Slider_Difference", "DV_Binary_Diff", "Warmth", "Personalization"]].groupby(["Warmth", "Personalization"]).mean()

                        Slider_Difference  DV_Binary_Diff
Warmth Personalization
0      0                   -100000.000000        0.500000
       1                   -266666.666667        0.666667
1      0                         0.000000        0.333333
       1                   -450000.000000        0.500000

In [66]:
df[["Warmth_Check", "Slider_Difference" ,"Warmth"]].groupby(["Warmth"]).mean()

        Warmth_Check  Slider_Difference
Warmth
0                3.6          -200000.0
1                5.6          -180000.0

In [65]:
df[["Personalization_Check", "Slider_Difference", "Personalization"]].groupby(["Personalization"]).mean()

                 Personalization_Check  Slider_Difference
Personalization
0                                  3.7           -40000.0
1                                  4.4          -340000.0